export const ADD_FEATURED_PRODUCTS = 'ADD_FEATURED_PRODUCTS'
export const ADD_NORMAL_PRODUCTS = 'ADD_NORMAL_PRODUCTS'
export const SET_CART_ITEM = 'SET_CART_ITEM'



export const SET_ORDER_SUBMIT = 'SET_ORDER_SUBMIT'
export const SET_REJECTED_ORDERS = 'SET_REJECTED_ORDERS'
export const SET_PROCESSING_ORDERS = 'SET_PROCESSING_ORDERS'
export const SET_COMPLETED_ORDERS = 'SET_COMPLETED_ORDERS'





export const SET_ERROR = 'SET_ERROR';