export const ADD_FEATURED_PRODUCTS = 'ADD_FEATURED_PRODUCTS'
export const ADD_NORMAL_PRODUCTS = 'ADD_NORMAL_PRODUCTS'
export const SET_CART_ITEM = 'SET_CART_ITEM'

export const SET_ERROR = 'SET_ERROR';